spring.application.name=study_management
# 1. データベース接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/study_db
spring.datasource.username=postgres
spring.datasource.password=hasuneko
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPAの設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. 日本時間の設定
spring.jackson.time-zone=Asia/Tokyo